### ISSUE TITLE
SMTP端口号

### ISSUE THREAD

**Issue by MakerFace** [Evyde/JLU.OA.AnnounceBot#1]
吉大学生邮箱mails.jlu.edu.cn的发送服务器的端口号是多少呢？

**Comment by Evyde** [comment]
是默认端口号。同时建议使用[@TechCiel](https://github.com/TechCiel)的版本https://github.com/TechCiel/Reachee
另外如果没有特殊需求，可以直接使用现有的服务，例如QQ群：923351800
